export const projectsData = [
  {
    id: 1,
    title: "Creative Art Work",
    category: "Ecommerce Store",
    image: "1.jpg",
    filterValue: "ecommerce",
    toBeRemoved: false,
  },
  {
    id: 2,
    title: "Flowers In Vases",
    category: "API Integration",
    image: "2.jpg",
    filterValue: "api",
    toBeRemoved: false,
  },
  {
    id: 3,
    title: "Art Design",
    category: "Web Maintenance",
    image: "3.jpg",
    filterValue: "maintenance",
    toBeRemoved: false,
  },
  {
    id: 4,
    title: "Open Books",
    category: "Web Development",
    image: "4.jpg",
    filterValue: "development",
    toBeRemoved: false,
  },
  {
    id: 5,
    title: "Open Books",
    category: "Ecommerce Store",
    image: "5.jpg",
    filterValue: "ecommerce",
    toBeRemoved: false,
  },
  {
    id: 6,
    title: "Open Books",
    category: "Web Maintenance",
    image: "6.jpg",
    filterValue: "maintenance",
    toBeRemoved: false,
  },
  {
    id: 7,
    title: "Work Station",
    category: "API Integration",
    image: "7.jpg",
    filterValue: "api",
    toBeRemoved: false,
  },
  {
    id: 8,
    title: "Flowers In Vases",
    category: "Web Development",
    image: "8.jpg",
    filterValue: "development",
    toBeRemoved: false,
  },
  {
    id: 9,
    title: "Creative Art Work",
    category: "Ecommerce Store",
    image: "9.jpg",
    filterValue: "ecommerce",
    toBeRemoved: false,
  },
];
